spring:
  datasource:
    url: jdbc:mysql://sql7.freesqldatabase.com:3306/sql7783016
    username: sql7783016
    password: mZGLA2VX53
    driver-class-name: com.mysql.cj.jdbc.Driver
# Connection pool settings
    hikari:
      minimum-idle: 5        # Minimum idle connections in the pool
      maximum-pool-size: 10  # Max connections in the pool, adjust based on your DB limit
      idle-timeout: 300000   # 5 minutes before idle connections are closed (ms)
      max-lifetime: 1800000  # 30 minutes max lifetime of a connection (ms)
      connection-timeout: 30000 # Max wait for a connection from the pool (ms)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: mariiasthh@gmail.com
    password: hnqhqvuublqgbpwn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
